# Generated by Django 3.2.9 on 2021-11-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalerie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='photo',
            field=models.ImageField(upload_to='media/img_equipement/'),
        ),
    ]
