# Generated by Django 3.2.9 on 2021-11-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalerie', '0002_alter_equipement_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='photo',
            field=models.ImageField(upload_to='animalerie/media/'),
        ),
    ]
