# Generated by Django 3.2.9 on 2021-11-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalerie', '0005_alter_animal_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='photo',
            field=models.ImageField(upload_to='id_animal'),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='photo',
            field=models.ImageField(upload_to='id_equipement'),
        ),
    ]
